/* ============================================================
   FARMRENT — data.js
   Seed data & localStorage schema
   ============================================================ */

const STORAGE_KEYS = {
  USERS:    'fr_users',
  EQUIP:    'fr_equip',
  BOOKINGS: 'fr_bookings',
  WISHLIST: 'fr_wishlist',
  CHATS:    'fr_chats',
  REVIEWS:  'fr_reviews',
  SESSION:  'fr_session',
};

const SEED_EQUIPMENT = [
  {
    id: 'e1',
    name: 'John Deere 5310 Tractor',
    cost: 1200,
    crops: ['Rice', 'Wheat', 'Sugarcane'],
    owner: 'Ramesh Kumar',
    ownerContact: '9876543210',
    image: 'https://tse4.mm.bing.net/th/id/OIP.iPVbhNcMBsK5-bKo3_gIVAHaFj?rs=1&pid=ImgDetMain&o=7&rm=3',
    icon: '🚜',
    category: 'Tractor',
    desc: '45 HP 4WD tractor in excellent condition. Available with or without operator.',
    available: true,
  },
  {
    id: 'e2',
    name: 'Paddy Transplanter',
    cost: 600,
    crops: ['Rice', 'Paddy'],
    owner: 'Suresh Patel',
    ownerContact: '9988776655',
    image: 'https://th.bing.com/th/id/OIP.vjn8lqa0ea0GItL9_CXGvAHaFj?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3',
    icon: '🌾',
    category: 'Planting',
    desc: '6-row paddy transplanter. Covers 1 acre in about 4 hours.',
    available: true,
  },
  {
    id: 'e3',
    name: 'Combine Harvester',
    cost: 3500,
    crops: ['Wheat', 'Mustard', 'Soybean'],
    owner: 'Vijay Singh',
    ownerContact: '9111222333',
    image: 'https://th.bing.com/th/id/OIP.EiA1NywnG-VCkaHwiQ_I4wHaEj?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3',
    icon: '🌿',
    category: 'Harvester',
    desc: 'Self-propelled combine harvester. Includes operator and fuel.',
    available: false,
  },
  {
    id: 'e4',
    name: 'Rotavator',
    cost: 800,
    crops: ['Rice', 'Wheat', 'Cotton'],
    owner: 'Anand Rao',
    ownerContact: '9444555666',
    image: 'https://th.bing.com/th/id/OIP._aFigi3QJJRdJqQmpVbTlQHaEh?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3',
    icon: '⚙️',
    category: 'Tillage',
    desc: '72-blade rotavator, suitable for all soil types.',
    available: true,
  },
  {
    id: 'e5',
    name: 'Sprayer Pump',
    cost: 400,
    crops: ['Vegetables', 'Fruits', 'Cotton'],
    owner: 'Mohan Das',
    ownerContact: '9777888999',
    image: 'https://m.media-amazon.com/images/I/712lvboMurL._SX679_.jpg',
    icon: '💧',
    category: 'Spraying',
    desc: 'Battery-powered backpack sprayer with 16L tank.',
    available: true,
  },
  {
    id: 'e6',
    name: 'Seed Drill',
    cost: 950,
    crops: ['Wheat', 'Soybean', 'Maize'],
    owner: 'Kiran Reddy',
    ownerContact: '9222333444',
    image: 'https://tse3.mm.bing.net/th/id/OIP.TKbAd3ik7RuFdCw8XM-jHQHaHa?w=800&h=800&rs=1&pid=ImgDetMain&o=7&rm=3',
    icon: '🌱',
    category: 'Planting',
    desc: '9-tyne seed drill with fertilizer box. Perfect for row sowing.',
    available: true,
  },
  {
    id: 'e7',
    name: 'Power Tiller',
    cost: 700,
    crops: ['Vegetables', 'Paddy', 'Groundnut'],
    owner: 'Priya Nair',
    ownerContact: '9333444555',
    image: 'https://kj1bcdn.b-cdn.net/media/38976/vst-kisan.jpg',
    icon: '🔧',
    category: 'Tillage',
    desc: '8 HP power tiller, ideal for small and medium farms.',
    available: true,
  },
  {
    id: 'e8',
    name: 'Water Pump Set',
    cost: 350,
    crops: ['Rice', 'Vegetables', 'Sugarcane'],
    owner: 'Arjun Mehta',
    ownerContact: '9555666777',
    image: 'https://5.imimg.com/data5/SELLER/Default/2020/10/KG/LT/XM/5943095/img-4753-500x500.JPG',
    icon: '🪣',
    category: 'Irrigation',
    desc: '5 HP diesel water pump with 50 metre hose pipe.',
    available: true,
  },
];

const EQUIPMENT_ICONS = ['🚜', '🌾', '🌿', '⚙️', '💧', '🌱', '🔧', '🪣', '🚛', '⛏️', '🏗️', '🔩'];
